In [2]:
import numpy as np

from hw3_lib import Linear, Sigmoid, ReLU, CrossEntropyLoss, GradientDescentOptimizer

In [4]:
# NOTATION
# in the comments below
#     N is batch size.
#     in_features is the input size (not counting the bias)
#     out_features is the output size
#     C is number of classes (10 for this assignment)

# do not import any other libraries
# they are not needed and won't be available to the autograder
class Module:
    def __init__(self):
        pass

    def __call__(self, *args, **kwargs):
        return self.forward(args, kwargs)

    def forward(self, *x):
        raise NotImplementedError

    def backward(self, *g):
        raise NotImplementedError

In [14]:
A = np.array([[1, -1, 0, -4, 3], [0, -2, 3, -3, 2], [-1, 4, 5, -23, 0]])
print(A)
A[A<0] = 0
print(A)

[[  1  -1   0  -4   3]
 [  0  -2   3  -3   2]
 [ -1   4   5 -23   0]]
[[1 0 0 0 3]
 [0 0 3 0 2]
 [0 4 5 0 0]]


In [21]:
A = np.array([[1, 1, 1], [2, 2, 2]])
print(A + np.array([[1, 2, 3]]))
print(A.shape)
B = np.zeros(A.shape)
print(B)
print(A.shape[1])
for i in range(A.shape[1]):
    print(i)

[[2 3 4]
 [3 4 5]]
(2, 3)
[[0. 0. 0.]
 [0. 0. 0.]]
3
0
1
2


In [31]:
A = np.array([[1, 2, 3], [2, 1, 1]])
print(A/A.sum(axis = 1, keepdims = True))
print(np.exp(A))
print(A-np.max(A))
print(np.exp(A-np.max(A)))

[[0.16666667 0.33333333 0.5       ]
 [0.5        0.25       0.25      ]]
[[ 2.71828183  7.3890561  20.08553692]
 [ 7.3890561   2.71828183  2.71828183]]
[[-2 -1  0]
 [-1 -2 -2]]
[[0.13533528 0.36787944 1.        ]
 [0.36787944 0.13533528 0.13533528]]


In [34]:
A = np.array([[1, 1, 2], [2, 3, 1]])
B = np.array([[2, 3, 4], [1, 3, 4]])
print(A*B)

[[2 3 8]
 [2 9 4]]


In [42]:
for i in range(0, 15, 6):
    print(i)


0
6
12


In [48]:
yhats = np.array([[0, 1, 2, 9], [2, 3, 5, 0], [2, 12, 2, 5]])
yhat = yhats.argmax(axis = 1)
print(yhat)

[3 2 1]


In [49]:
def load_data():
    data_train = np.genfromtxt('training_data_student/train.csv', dtype=np.float64, delimiter=',')
    assert data_train.shape == (3000, 785)
    data_test = np.genfromtxt('training_data_student/test.csv', dtype=np.float64, delimiter=',')

    assert data_test.shape == (1000, 785)

    return {
        'train_x': data_train[:, :-1].astype(np.float64),
        'train_y': data_train[:, -1].astype(np.int64),
        'test_x': data_test[:, :-1].astype(np.float64),
        'test_y': data_test[:, -1].astype(np.int64),
    }

In [51]:
dataset = load_data()

In [53]:
train_x, train_y = dataset['train_x'], dataset['train_y']
test_x, test_y = dataset['test_x'], dataset['test_y']


In [60]:
a = train_y.argmax()
print(a)
print(train_y)

2700
[0 0 0 ... 9 9 9]


In [67]:
A = np.array([[1, 2, 4], [2, 3, 2]])
n, m = A.shape
print(n)
print(m)
print(type(A))
(a, b) = A.shape
print(a, b)

2
3
<class 'numpy.ndarray'>
2 3


In [75]:
a = np.array([[1, 2, 8], [1, 2, 4]])
print(a - np.max(a, axis = 1, keepdims = True))

[[-7 -6  0]
 [-3 -2  0]]
